### ISSUE TITLE
getting the following error

### ISSUE THREAD

**Issue by dimitrieh** [creeperyang/sketch-measure-cli#1]
![image](https://user-images.githubusercontent.com/429659/29171812-0b79f5b8-7dde-11e7-8225-bc564f0ae7d1.png)

maybe my node setup, but just to be sure

**Comment by creeperyang** [comment]
It looks like that your sketch file format is not correct.

Make sure your sketch file's version **greater than 43** (saved by sketch>=43). Because the file(>=43) has a new format (zipped JSONs).

So if it is, upgrade your sketch, re-save the file and retry.

**Comment by dimitrieh** [comment]
Thanks @creeperyang , was unfortunate to just pick out an old file. Got it working 😉

**Comment by dimitrieh** [comment]
@creeperyang any other known bugs btw? or should this function exactly the same as sketch-measure?

**Comment by creeperyang** [comment]
I did much to make it work as `sketch-measure`. However `sketch-measure` uses some API that only exists in sketch app, so It's not exactly the same.

And knowns issues:

- Only artboards exported.
- Some deep layers may got loss (no measure info).
- Some text attributes got loss.

**Comment by dimitrieh** [comment]
cool stuff still! thanks for your efforts here
